# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip
  - pdf

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/setuptools.requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/zh_CN/conf.py
